# Generated by Django 5.0.6 on 2024-07-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('user_agent', models.CharField(max_length=255)),
                ('expired_datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
    ]
