# Generated by Django 5.0.6 on 2024-07-28 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSession',
            new_name='Session',
        ),
    ]
