version: "2.3"
services:
  # Nginx server
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./nginx/config:/etc/nginx           # Nginx configuration
      - ./nginx/logs:/var/log/nginx         # Nginx log folder
      - ../statics:/opt/apps/static      # Static folder
    command: /tmp/run_nginx.sh              # Create nginx config file from config template
    environment:
      - DOLLAR=$$
    env_file:
      - ./.env
    depends_on:
      - django
    restart: always

  # Django server
  django:
    build:
      context: ../
      dockerfile: docker/django/Dockerfile
    expose:
      - ${Django_PORT}
    volumes:
      - ../src:/src                     # Source code
      - ../databases:/databases         # Database folder
      - ../logs:/logs                   # Django logger
      - ../.env:/.env                   # Django logger
      - ../statics:/statics
    command: bash -c "cd src
                    && python manage.py collectstatic --noinput
                    && python manage.py migrate
                    && python manage.py migrate --database authentication
                    && python manage.py migrate --database session
                    && python manage.py runserver 0.0.0.0:${DJANGO_PORT}"
    restart: always
networks:
  default:
    external: true
    name: ${COMPOSE_PROJECT_NAME}_network
