# Generated by Django 5.0.6 on 2024-07-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_key',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
